# Generated by Django 5.0.6 on 2024-05-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_videoscontent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VideosContent",
            new_name="VideoContent",
        ),
    ]
