# Generated by Django 5.0.6 on 2024-05-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_rename_videoscontent_videocontent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videocontent",
            old_name="url_vidio",
            new_name="url_video",
        ),
    ]
